### ISSUE TITLE
Race condition with arbitrable contracts

### ISSUE THREAD

**Issue by satello** [kleros/kleros-api#138]
An unforeseen consequence of the design choice to load and store the contract instance in the ContractImplementation class and to apply it to both arbitrable and arbitrator contracts is that we have race conditions between notifications or other background tasks and user actions.

For example: When we refresh the page while loading a contract in `kleros.tech` there is a race condition between notifications which is setting the arbitrable instance and the user who is trying to load a different arbitrable contract to fetch data.

**Comment by epiqueras** [comment]
Notifications should use their own instance.

**Comment by satello** [comment]
Yeah that's what I did. We need to further separate disputes and notifications however. There is still going to be a race condition between kleros.disputes.getDisputeData and notifications since Disputes also has to be passed the "internal" instance of arbitrable contract because it registers some notification callbacks

**Comment by satello** [comment]
I think some of the bulkiness and problematic listeners will get sorted out when the store cutdown is reflected in the api. This will eliminate the timestamp event callbacks which is what the majority of the dispute event listeners are for. What do you think about having each notification handler spin up its own instance of arbitrable contract? It's bulky. But using them as throwaway classes would completely fix the problem

**Comment by epiqueras** [comment]
Then we can have two or more “internal” instances. Let’s try to get away
with the least amount possible while still having no race conditions.
