### ISSUE TITLE
Don't Show "0" PNK Shift, Show "No PNK won." Instead

### ISSUE THREAD

**Issue by epiqueras** [kleros/kleros-api#169]

**Comment by clesaege** [comment]
No need to notify if nothing happens. Let's just not show anything.
Telling people they haven't won anything does not really provides info and is not driving engagement either, so better not to tell anything (I'm speaking about the notification).

**Comment by epiqueras** [comment]
But it also tells them that the dispute was resolved/executed.

**Comment by epiqueras** [comment]
Maybe the notification should be: "Dispute resolved.[ You won/lost X PNK.]".
