### ISSUE TITLE
Handle errors in interactions with contracts

### ISSUE THREAD

**Issue by satello** [kleros/kleros-api#35]
After tx's are successfully mined there can still be errors. For example voting during the wrong period will be rejected by the contract. However at the moment we are only throwing errors if a tx fails to be submitted. We need a way to watch tx's and revert store updates/state if an action is unsuccessful

**Comment by epiqueras** [comment]
Relates to #81

**Comment by epiqueras** [comment]
#99 Fixes this when estimateGas catches the error. We still need to handle the cases where it doesn't.

**Comment by epiqueras** [comment]
@satello 
Isn't this just a matter of making sure that on-chain modifications happen before off-chain ones and in the same `try` block?

`truffle-contract` instance methods block until a transaction receipt is received.

Voting would throw if not in the `vote` period right?

**Comment by satello** [comment]
yes I suppose so. This issue may not be relevant anymore
