### ISSUE TITLE
Add `createdAt` Throughout The API

### ISSUE THREAD

**Issue by epiqueras** [kleros/kleros-api#66]
The new front end design requires some dates that we are missing.

The first that come to mind are:

* Dispute `createdAt`.
* Evidence `submittedAt`.
* Ruling `ruledAt`.

We should also return all timestamps as milliseconds since epoch.

**Comment by satello** [comment]
`ruledAt` is going to be difficult to do reliably. I am planning on using the `block.timestamp` from events to peg `createdAt` for the other two. We can keep it in the store but this data can potentially be lost and we won't be able to recover it

**Comment by epiqueras** [comment]
@satello 
Can we set `ruledAt` to the time when `Period.Vote =>Period.Appeal`?

**Comment by epiqueras** [comment]
Maybe inside `KlerosWrapper.passPeriod`?

**Comment by satello** [comment]
Oh you mean dispute `ruledAt`. I was thinking a timestamp for when a juror ruled. Still are going to have the same issue in that if the store goes down or data gets lost it will be difficult to get that timestamp back. That might even be trickier. We have that same problem of not knowing which disputes are in the current session without iterating over all of them. We are going to do that for `appealPossible` notifications via `passPeriod` so I will add that to the store in that handler as well. Won't totally solve the problem but we will at least have something in the store

**Comment by epiqueras** [comment]
@satello 
Great.

I don't think it's critical for these timestamps to be persisted on-chain right now. They are more for UI/UX really.
