### ISSUE TITLE
API Lets You Vote After Voting Period is Over

### ISSUE THREAD

**Issue by epiqueras** [kleros/kleros-api#81]
Even in a different session.

**Comment by satello** [comment]
I don't think this is an issue necessarily. I don't think we should bake the dispute flow into the API if it can be helped. The api is just there to provide an interface to the contracts so if an user wants to be able to submit a vote I think we should let them call that function whenever. What we can do is use `estimateGas` on all of our calls to see if they will fail beforehand and then return an error to save users gas. See #56

**Comment by epiqueras** [comment]
The problem is that it changes values in the store and that is confusing
for the user when he looks at the UI.

It would be worst for the UI to have to hide it based on some logic. The
API should answer the UI’s questions, not force it to infer from it.

**Comment by satello** [comment]
Yes that is an issue. We can fix that
